MONGODB_HOST: mongodb.daws88s.sbs
REDIS_HOST: redis.daws88s.sbs
CATALOGUE_HOST: catalogue.daws88s.sbs
CART_HOST: cart.daws88s.sbs
MYSQL_HOST: mysql.daws88s.sbs
USER_HOST: user.daws88s.sbs
RABBITMQ_HOST: rabbitmq.daws88s.sbs
SHIPPING_HOST: shipping.daws88s.sbs
PAYMENT_HOST: payment.daws88s.sbs
